apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "integreatly.org/v1alpha1",
          "kind": "BlobStorage",
          "metadata": {
            "labels": {
              "productName": "ProductName"
            },
            "name": "example-blobstorage"
          },
          "spec": {
            "secretRef": {
              "name": "example-blobstorage-sec"
            },
            "tier": "development",
            "type": "REPLACE_ME"
          }
        },
        {
          "apiVersion": "integreatly.org/v1alpha1",
          "kind": "Postgres",
          "metadata": {
            "labels": {
              "productName": "productName"
            },
            "name": "example-postgres"
          },
          "spec": {
            "secretRef": {
              "name": "example-postgres-sec"
            },
            "tier": "development",
            "type": "REPLACE_ME"
          }
        },
        {
          "apiVersion": "integreatly.org/v1alpha1",
          "kind": "PostgresSnapshot",
          "metadata": {
            "name": "example-postgressnapshot"
          },
          "spec": {
            "resourceName": "REPLACE_ME"
          }
        },
        {
          "apiVersion": "integreatly.org/v1alpha1",
          "kind": "Redis",
          "metadata": {
            "labels": {
              "productName": "productName"
            },
            "name": "example-redis"
          },
          "spec": {
            "secretRef": {
              "name": "example-redis-sec"
            },
            "tier": "development",
            "type": "REPLACE_ME"
          }
        },
        {
          "apiVersion": "integreatly.org/v1alpha1",
          "kind": "RedisSnapshot",
          "metadata": {
            "name": "example-redissnapshot"
          },
          "spec": {
            "resourceName": "REPLACE_ME"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-unknown
    operators.operatorframework.io/project_layout: go
  name: cloud-resources.v0.18.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: BlobStorage is the Schema for the blobstorages API
      kind: BlobStorage
      name: blobstorages.integreatly.org
      version: v1alpha1
    - description: Postgres is the Schema for the postgres API
      kind: Postgres
      name: postgres.integreatly.org
      version: v1alpha1
    - description: PostgresSnapshot is the Schema for the postgressnapshots API
      kind: PostgresSnapshot
      name: postgressnapshots.integreatly.org
      version: v1alpha1
    - description: Redis is the Schema for the redis API
      kind: Redis
      name: redis.integreatly.org
      version: v1alpha1
    - description: RedisSnapshot is the Schema for the redissnapshots API
      kind: RedisSnapshot
      name: redissnapshots.integreatly.org
      version: v1alpha1
  description: Cloud Resources description. TODO.
  displayName: Cloud Resources
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - config.openshift.io
          resources:
          - infrastructures
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          - configmaps
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - prometheusrules
          verbs:
          - '*'
        serviceAccountName: cloud-resource-operator
      deployments:
      - name: cloud-resource-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: cloud-resource-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: cloud-resource-operator
            spec:
              containers:
              - command:
                - cloud-resource-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: cloud-resource-operator
                - name: TAG_KEY_PREFIX
                  value: integreatly.org/
                image: quay.io/integreatly/cloud-resource-operator:v0.18.0
                imagePullPolicy: Always
                name: cloud-resource-operator
                resources: {}
              serviceAccountName: cloud-resource-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - pods/exec
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - cloud-resource-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - integreatly
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - integreatly.org
          resources:
          - '*'
          - smtpcredentialset
          - redis
          - postgres
          - redissnapshots
          - postgressnapshots
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - prometheusrules
          verbs:
          - '*'
        - apiGroups:
          - config.openshift.io
          resources:
          - '*'
          - infrastructures
          - schedulers
          - featuregates
          - networks
          - ingresses
          - clusteroperators
          - authentications
          - builds
          verbs:
          - '*'
        - apiGroups:
          - cloudcredential.openshift.io
          resources:
          - credentialsrequests
          verbs:
          - '*'
        serviceAccountName: cloud-resource-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cloud-resources
  links:
  - name: Cloud Resources
    url: https://cloud-resources.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.18.0
