language: go

sudo: required

go:
  - 1.13.x

git:
  depth: 1

stages:
  - test

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/securego/gosec/cmd/gosec

jobs:
  include:
    - stage: test
      script:
        - go get github.com/mattn/goveralls
        - make code/check
        - make test/unit/ci
        - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
        - make code/audit