apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: cloud-resource-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - cloud-resource-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - integreatly
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - integreatly.org
  resources:
  - '*'
  - smtpcredentialset
  - redis
  - postgres
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  verbs:
  - '*'
  resources:
  - '*'
  - infrastructures
  - schedulers
  - featuregates
  - networks
  - ingresses
  - clusteroperators
- apiGroups:
  - cloudcredential.openshift.io
  verbs:
  - '*'
  resources:
  - credentialsrequests